; use 'default' to use the base game color 
; and write custom color values as either 'r, g, b'
; or as hex values like 'FF0000' (no leading '#'!)

[ColorsSingleplayer]
Primary = default
Secondary = default

[ColorsAtlas]
Primary = default
Secondary = default

[ColorsPBody]
Primary = default
Secondary = default


[Files]
; the dlc folder to use, ensure that the dlc folder exists and doesn't contain any other vpk files
DlcFolder = 5
; setting this to true will skip patching the client, should only be set if a game update broke stuff
NoClientPatching = false
